name: Submit dependency graph
on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit
      - name: Run a build and generate the dependency graph which will be submitted post-job
        run: |
          ./gradlew \
          -PgithubUsername="${{ secrets.ARTIFACTORY_USERNAME }}" \
          -PgithubPassword="${{ secrets.ARTIFACTORY_API_KEY }}" \
          assemble -x test
